BookApp/urls.py
from django.urls import path
from . import views

app_name = 'BookApp'

urlpatterns = [
    path("book-search/"            , views.bookSearchView      , name="bookSearch"),
    path("book-list/"              , views.bookListView        , name="bookList"),
    path('book-detail/<int:pk>'            , views.bookDetailView      , name='bookDetail'),
    path(""                        , views.myBookView          , name="myBook"),
    path("myBook-detail/<str:id>" , views.myBookDetailView    , name="myBookDetail"),
    path("myBook-delete/" , views.myBookDeleteView    , name="myBookDelete"),
    path("myBook-update/<str:id>" , views.myBookUpdateView    , name="myBookUpdate"),
    path("newBook/"               , views.newBookView         , name="newBook"),
    path("login/"                  , views.loginView           , name="login"),
    path("logout/"                 , views.logoutView          , name="logout"),
    path("content-Create/<str:id>"           , views.contentCreateView     , name="contentCreate"),
    path("content-Delete/<str:id>/<str:flag>"   , views.contentDeleteView     , name="contentDelete"),
    path("content-Update/<str:id>/<str:flag>"   , views.contentUpdateView     , name="contentUpdate"),
    path("userInformation/"   , views.userInformationView     , name="userInformation"),
    path("userUpdate/"   , views.userUpdateView     , name="userUpdate"),
    path("allContent/"   , views.allContentView     , name="allContent"),
]

BookProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BookApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookApp/forms.py
from django import forms
from .models import Book, Stage, Language, Category
from django.contrib.auth.models import User

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'title',
                    'class': 'single',
                }
            ),
            'author': forms.TextInput(
                attrs={
                    'placeholder': 'author',
                    'class': 'single',
                }
            ),
            'isbn': forms.TextInput(
                attrs={
                    'placeholder': 'isbn',
                    'class': 'single',
                }
            ),
            'publishedDate': forms.TextInput(
                attrs={
                    'placeholder': 'publishedDate',
                    'class': 'single',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'placeholder': 'description',
                    'class': 'multi',
                }
            ),
            'impression': forms.Textarea(
                attrs={
                    'placeholder': 'impression',
                    'class': 'multi',
                }
            ),
            'page': forms.NumberInput(
                attrs={
                    'min': '0',
                }
            ),
            'review': forms.NumberInput(
                attrs={
                    'min': '1',
                    'max': '5',
                }
            ),

        }    


class StageForm(forms.ModelForm):
    class Meta:
        model = Stage
        fields = "__all__"

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'stage',
                    'class': 'single',
                }
            ),
        }


class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = "__all__"

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'stage',
                    'class': 'single',
                }
            ),
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'stage',
                    'class': 'single',
                }
            ),
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'username', 'email')

        widgets = {
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'last_name',
                    'class': 'single',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'first_name',
                    'class': 'single',
                }
            ),
            'username': forms.TextInput(
                attrs={
                    'placeholder': 'username',
                    'class': 'single',
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'email',
                    'class': 'single',
                }
            ),
        }


class AccountForm(forms.Form):
    username = forms.CharField(
        max_length = 30,
        widget = forms.TextInput(
            attrs = {
                'placeholder':'Username',
                'class':'single'
            }
        )
    )

    password = forms.CharField(
        max_length = 128,
        widget = forms.PasswordInput(
            attrs={
                'placeholder':'Password', 
                'class':'single'
            }
        )
    )

BookApp/views.py
# Copyright 2022 Kokai Sakaguchi
# ビュー

from django.shortcuts import render, redirect
import requests
import random
from .forms import BookForm, StageForm, LanguageForm, CategoryForm, UserForm, AccountForm
from .models import Book, Stage, Language, Category
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# 書籍情報が格納されたリストから必要な情報だけを抜き取る。
def get_book(items_list):
    data = []    # 得られた書籍情報の中の必要な情報だけを格納する。

    # 必要な情報だけを取り出してdataに格納。
    for items in items_list:
        info = items["volumeInfo"]
        dic = {}    # 書籍情報の各項目を格納する辞書型データ。

        if 'id' not in items.keys():    # ID
            id = ""
        else:
            id = items['id']

        if 'title' not in info.keys():    # タイトル。
            title = ""
        else:
            title = info['title']
            title = title.replace('/', '・')    # タイトル名に「/」があれば、「・」に置き換える。（URLパラメータの関係より）

        if 'authors' not in info.keys():    # 著者。
            author = ""
        else:
            author = info['authors'][0]

        if 'publishedDate' not in info.keys():    # 出版日。
            publishedDate = ""
        else:
            publishedDate = info['publishedDate']

        if 'imageLinks' not in info.keys():    # 表紙画像のアドレス。
            bookCover = ""
        else:
            bookCover = info['imageLinks']['smallThumbnail']

        if 'description' not in info.keys():    # あらすじ。
            description = ""
        else:
            description = info['description']

        if 'pageCount' not in info.keys():    # ページ数。
            page = ""
        else:
            page = info['pageCount']

        if 'categories' not in info.keys():    # カテゴリー。
            category = ""
        else:
            category = info['categories'][0]

        if 'language' not in info.keys():    # 言語。
            language = ""
        else:
            language = info['language']

        if 'industryIdentifiers' not in info.keys():    # ISBN。
            isbn = ""
        else:
            a = info['industryIdentifiers']
            isb = a[0]
            isbn = isb['identifier']

        # 各項目を辞書に格納し、リストに追加する。
        dic["id"] = id
        dic["title"] = title
        dic["author"] = author
        dic["publishedDate"] = publishedDate
        dic["bookCover"] = bookCover
        dic["description"] = description
        dic["page"] = page
        dic["category"] = category
        dic["language"] = language
        dic["isbn"] = isbn
        data.append(dic)

    return data    # 書籍情報の返却。


# APIでの書籍検索ページのビュー。
def bookSearchView(request):
    template_name = "bookSearch.html"    # テンプレートファイル。
    form = BookForm(request.POST or None)    # 書籍を登録するためのフォームの初期化。

    # テンプレートで表示するデータ。
    app_data = {
        'form': form, 
    }

    return render(request, template_name, app_data)


# APIでの書籍一覧ページのビュー。
def bookListView(request):
    template_name = "bookList2.html"    # テンプレートファイル。
    data = []    # 書籍情報を格納するリスト。
    form = BookForm(request.POST or None)    # 書籍を登録するためのフォームの初期化。

    if request.method == 'POST':
        # formで得られた値を取得。
        title = form.data['title']
        author = form.data['author']
        isbn = form.data['isbn']

        url = "https://www.googleapis.com/books/v1/volumes?q="    # GooglBooksAPIの元となるURL。

        # Web-APIにアクセスするためのURLを作成。
        if title:
            url += "intitle:"
            url += title
        if author:
            url += "+inauthor:"
            url += author
        if isbn:
            url += "+isbn:"
            url += isbn
        url += "&maxResults=40"    # 取得する書籍を40件までに限定。

        try:    # 通常処理。
            response = requests.get(url).json()    # 書籍情報の取得し、json形式に変換。

            if 'totalItems' not in response.keys():
                book_len = 0
            else:
                book_len = response["totalItems"]
                if 'items' in response.keys():
                    data = get_book(response["items"])    # 得られた書籍情報の中の必要な情報だけを格納する。

        except requests.exceptions.RequestException as e:    # 例外処理。
            return redirect('BookApp:myBook')    # マイページのビューにリダイレクトする。

    # テンプレートで表示するデータ。
    myapp_data = {
        'total': book_len,
        'obj': data,
        'title': title,
        'author': author,
        'isbn': isbn,
        'form': form,
    }

    return render(request, template_name, myapp_data)


# APIでの書籍詳細ページのビュー。
@login_required    # ログイン状態であるかを判定する。
def bookDetailView(request, pk):
    template_name = "bookDetail.html"    # テンプレートファイル。

    try:
        # データベースに保存
        if pk == 2:
            form = BookForm(request.POST, request.FILES)    # フォームの内容を取得。
            form.save()    # フォームで取得した値をデータベースに保存。
            return redirect('BookApp:myBook')    # マイページにリダイレクトする。
        elif pk == 1:
            # フォームの初期化情報
            print(request.POST.get('param-title'))
            initial_dict = {
                'title': request.POST.get('param-title'),
                'author': request.POST.get('param-author'),
                'publishedDate': request.POST.get('param-publishedDate'),
                'description': request.POST.get('param-description'),
                'isbn': request.POST.get('param-isbn'),
                'page': request.POST.get('param-page'),
                'order' : len(Book.objects.filter(user=request.user.id)) + 1,
                'category': request.POST.get('param-category'),
                'language': request.POST.get('param-language'),
            }

            form = BookForm(initial=initial_dict)    # 登録するための書籍情報のフォームを初期化
    except:
        return redirect('BookApp:myBook')    # マイページにリダイレクトする。

    # テンプレートで表示するデータ。
    myapp_data = {
        'bookCover_url': request.POST.get('param-image'),
        'form': form,
    }

    return render(request, template_name, myapp_data)


# マイページのビュー。
@login_required    # ログイン状態であるかを判定する。
def myBookView(request):
    template_name = "myBook.html"    # テンプレートファイル。

    try:    # 通常処理。
        # データベースに保存
        if request.method == 'POST':
            form = BookForm(request.POST, request.FILES)    # フォームの内容を取得。
            if form.data['title']:
                obj = Book.objects.filter(title=form.data['title'])    # 特定のユーザの全書籍データの取得。
            elif form.data['author']:
                obj = Book.objects.filter(author=form.data['author'])    # 特定のユーザの全書籍データの取得。
            elif form.data['isbn']:
                obj = Book.objects.filter(isbn=form.data['isbn'])    # 特定のユーザの全書籍データの取得。
            elif form.data['review']:
                obj = Book.objects.filter(review=form.data['review'])    # 特定のユーザの全書籍データの取得。
            elif form.data['order']:
                obj = Book.objects.filter(order=form.data['order'])    # 特定のユーザの全書籍データの取得。
            elif form.data['category']:
                obj = Book.objects.filter(category=Category.objects.filter(id=form.data['category'])[0].id)    # 特定のユーザの全書籍データの取得。
            elif form.data['language']:
                obj = Book.objects.filter(language=Language.objects.filter(id=form.data['language'])[0].id)    # 特定のユーザの全書籍データの取得。
            elif form.data['stage']:
                obj = Book.objects.filter(stage=Stage.objects.filter(id=form.data['stage'])[0].id)    # 特定のユーザの全書籍データの取得。

        else:
            obj = Book.objects.filter(user=request.user.id).order_by('order').reverse()    # 現在、ログインしているユーザの全書籍データの取得。
            form = BookForm(request.POST or None)    # 書籍を登録するためのフォームの初期化。
    except:
        return redirect('BookApp:myBook')    # マイページにリダイレクトする。

    for item in obj:
        if item.registerDate is not None:
            item.registerDate = item.registerDate.strftime('%Y-%m-%d %H:%M:%S')
        if item.updateDate is not None:
            item.updateDate = item.updateDate.strftime('%Y-%m-%d %H:%M:%S')
 
    # テンプレートで表示するデータ。
    myapp_data = {
        'total': len(obj),
        'obj': obj,
        'form': form,
    }

    return render(request, template_name, myapp_data)


# データベース上の全書籍一覧のビュー。
def allBookView(request):
    template_name = "allBook.html"    # テンプレートファイル。

    obj = Book.objects.all().order_by('order').reverse()    # データベースに登録されている全書籍データの取得。

    # テンプレートで表示するデータ。
    myapp_data = {
        'total': len(obj),
        'obj': obj,
    }

    return render(request, template_name, myapp_data)


# マイブックの詳細ページのビュー。
@login_required    # ログイン状態であるかを判定する。
def myBookDetailView(request, id):
    template_name = "myBookDetail.html"    # テンプレートファイル。

    obj = Book.objects.get(pk=id)    # 取得したIDに該当する書籍データの取得。

    # フォームの初期化情報
    initial_dict = {
        'title': obj.title,
        'author': obj.author,
        'publishedDate': obj.publishedDate,
        'description': obj.description,
        'isbn': obj.isbn,
        'page': obj.page,
        'registerDate' : obj.registerDate,
        'impression' : obj.impression,
        'review' : obj.review,
        'order' : obj.order,
        'stage' : obj.stage,
        'category': obj.category,
        'language': obj.language,
    }

    form = BookForm(request.POST or None, initial=initial_dict)    # 書籍を登録するためのフォームの初期化。

    # テンプレートで表示するデータ。
    myapp_data = {
        'obj': obj,
        'form': form,
    }

    return render(request, template_name, myapp_data)


# 書籍の削除を行うビュー。
@login_required    # ログイン状態であるかを判定する。
def myBookDeleteView(request):
    try:    # 通常処理。
        result = request.POST.getlist('delete')
        Book.objects.filter(id__in=result).delete()    # 書籍の削除。
    except:    # 例外処理。
        return redirect('BookApp:myBook')    # マイページにリダイレクトする。

    return redirect('BookApp:myBook')    # マイページにリダイレクトする。


# 書籍の更新を行うビュー。
@login_required    # ログイン状態であるかを判定する。
def myBookUpdateView(request, id):
    try:    # 通常処理。
        member = get_object_or_404(Book, id=id)    # 取得したIDに該当する書籍データの取得。
        if request.method == "POST":

BookApp/templates/allContent.html
<!-- テンプレートファイルの継承 -->
{% extends "base.html" %}

<!-- Title -->
{% block title %}All Content{% endblock %}

{% block css %}
<!-- Style -->
<!-- CSSファイルの読み込み -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/allContent.css'  %}" />
{% endblock %}

<!-- Body -->
{% block content %}
<!-- ヘッドライン -->
<a href="{% url 'BookApp:allContent' %}"><p class="headline">ALL CONTENT</p></a>


<div class="content">
    <div class="content-list">
        <p><a href="{% url 'BookApp:contentCreate' 'stage-create' %}" target="blank">Stage</a></p><br>
        <ul>
            {% for item in stage %}
            <li>{{ item.title }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="content-list">
        <p><a href="{% url 'BookApp:contentCreate' 'language-create' %}" target="blank">Language</a></p><br>
        <ul>
            {% for item in language %}
            <li>{{ item.title }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="content-list">
        <p><a href="{% url 'BookApp:contentCreate' 'category-create' %}" target="blank">Category</a></p><br>
        <ul>
            {% for item in category %}
            <li>{{ item.title }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

BookApp/templates/base.html
<!-- Copyright 2022 Kokai Sakaguchi -->
<!-- ベーステンプレート -->

<!DOCTYPE html>

<!-- 言語を日本語に設定 -->
<html lang="ja">
    <!-- Header -->
    <head>
        <!-- 文字コードをutf-8に設定 -->
        <meta charset="utf-8">
        <!-- Title -->
        <title>{% block title %}{% endblock %}</title>

        <!-- Style -->
        <!-- CSSファイルの読み込み -->
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
        {% block css %}{% endblock %}
    </head>

    <!-- Body -->
    <body>
        <div class="gnavi__wrap">
            <div class="gnavi__list">
                <a href="{% url 'BookApp:myBook' %}">My Book</a>
            </div>
            <div class="gnavi__list">
                <a href="#">Register Book</a>
                <div class="dropdown__lists">
                    <div class="dropdown__list">
                        <a href="{% url 'BookApp:bookSearch' %}">By API</a>
                    </div>
                    <div class="dropdown__list">
                        <a href="{% url 'BookApp:newBook' %}">By Empty</a>
                    </div>
                </div>
            </div>
            <div class="gnavi__list">
                <a href="#">Create</a>
                <div class="dropdown__lists">
                    <div class="dropdown__list">
                        <a href="{% url 'BookApp:allContent' %}">All Contents</a>
                    </div>
                    <div class="dropdown__list">
                        <a href="{% url 'BookApp:contentCreate' 'stage-create' %}">Create Stage</a>
                    </div>
                    <div class="dropdown__list">
                        <a href="{% url 'BookApp:contentCreate' 'language-create' %}">Create Language</a>
                    </div>
                    <div class="dropdown__list">
                        <a href="{% url 'BookApp:contentCreate' 'category-create' %}">Create Category</a>
                    </div>
                </div>
            </div>
            <div class="gnavi__list">
                <a href="#">User</a>
                <div class="dropdown__lists">
                    {% if user.is_authenticated %}
                    <div class="dropdown__list">
                        <a href="{% url 'BookApp:userInformation' %}">User Information</a>
                    </div>
                    <div class="dropdown__list">
                        <a href="{% url 'BookApp:logout' %}">Logout</a>
                    </div>
                    {% else %}
                    <div class="dropdown__list">
                        <a href="{% url 'BookApp:login' %}">Login</a>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="gnavi__list">
                <a href="#">Other</a>
            </div>

        </div>

        {% block content %}{% endblock %}

        <footer id="footer">
            <p>Book App</p>
            <p>Kokai Sakaguchi Copyright (C) All Rights Reserved.</p>
        </footer>

        <!-- Script -->        
        {% block js %}{% endblock %}
    </body>
</html>


<!-- 参照ページ -->
<!-- トップダウンメニュー -->
<!-- https://www.asobou.co.jp/blog/web/css-dropdown -->

BookApp/templates/bookDetail.html
<!-- テンプレートファイルの継承 -->
{% extends "base.html" %}

<!-- Title -->
{% block title %}Book Register{% endblock %}

<!-- Style -->
{% block css %}
<!-- CSSファイルの読み込み -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bookDetail.css' %}" />
{% endblock %}


<!-- Body -->
{% block content %}
<!-- ヘッドライン -->
<a href="#"><p class="headline">CREATE BOOK</p></a>


<!-- 書籍の詳細情報 -->
<div class="content">
    <div class="newBook">
        <div class="img-flex">
            <!-- 書籍の表紙画像 -->
            {% load static %}
            <div class="card-img"><img src="{% static 'image/bookCover.png' %}" id="preview" alt=""></div>

            <!--デフォルト画像（GoogleBooksAPIに登録されている画像）があるページへのリンク-->
            <div class="card-img"><a href="{{ bookCover_url }}" target="_blank"><img src="{{ bookCover_url }}" alt=""></a></div>

        </div>
        <!-- 書籍の全項目 -->
        <div class="card-text">
            <form name="form1" action="{% url 'BookApp:bookDetail' 2 %}" method="POST" enctype="multipart/form-data" onSubmit="return check()">
                {% csrf_token %}    <!-- CSRF(クロスサイト・リクエスト・フォージェリ)対策 -->
                <ul>
                    <li><span class="index">IMAGE</span><p>{{ form.bookCover }}</p></li>
                    <li><span class="index">TITLE</span><p>{{ form.title }}</p></li>
                    <li><span class="index">AUTHOR</span><p>{{ form.author }}</p></li>
                    <li><span class="index">PUBLISHEDDATE</span><p>{{ form.publishedDate }}</p></li>
                    <li><span class="index">DESCRIPTION</span><p>{{ form.description }}</p></li>
                    <li><span class="index">ISBN</span><p>{{ form.isbn }}</p></li>
                    <li><span class="index">PAGE</span><p>{{ form.page }}</p></li>
                    <li><span class="index">IMPRESSION</span><p>{{ form.impression }}</p></li>
                    <li><span class="index">REVIEW</span><p>{{ form.review }}</p></li>
                    <li><span class="index">CATEGORY</span><a href="{% url 'BookApp:contentCreate' 'stage-create' %}" target="_blank">Create Category</a><p><label class="selectbox-001">{{ form.category }}</label></p></li>
                    <li><span class="index">LANGUAGE</span><a href="{% url 'BookApp:contentCreate' 'language-create' %}" target="_blank">Create Language</a><p><label class="selectbox-001">{{ form.language }}</label></p></li>
                    <li><span class="index">STAGE</span><a href="{% url 'BookApp:contentCreate' 'category-create' %}" target="_blank">Create Stage</a><p><label class="selectbox-001">{{ form.stage }}</label></p></li>
                    <input type="hidden" name="user" value="{{ user.id }}">
                </ul>
                
                <!-- 登録ボタン -->
                <button type="submit" name="submit" class="button">Register</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}


<!-- Script -->
{% block js %}
    <!-- JavaScriptファイルの読み込み -->
    {% load static %}
    <script src="{% static 'js/bookCover.js' %}"></script>
    <script>
        function check(){
            if(window.confirm('Do you register this book?')){ // 確認ダイアログを表示
                return true;
            }
            else{ // 「キャンセル」時の処理
                return false;
            }
        }
    </script>
{% endblock %}

BookApp/templates/contentCreate.html
<!-- テンプレートファイルの継承 -->
{% extends "base.html" %}

<!-- Title -->
{% block title %}Create Content{% endblock %}

{% block css %}
<!-- Style -->
<!-- CSSファイルの読み込み -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contentCreate.css'  %}" />
{% endblock %}

<!-- Body -->
{% block content %}
<!-- ヘッドライン -->
<a href="{% url 'BookApp:contentCreate' 'stage-create' %}"><p class="headline">CREATE STAGE</p></a>


<div class="content">
    {% if flag == 'stage-create' %}
    <form class="search_item" name="form1" action="{% url 'BookApp:contentCreate' 'stage-create' %}" method="POST" class="search_form" onsubmit="return check1()">
    {% elif flag == 'language-create' %}
    <form class="search_item" name="form1" action="{% url 'BookApp:contentCreate' 'language-create' %}" method="POST" class="search_form" onsubmit="return check1()">
    {% elif flag == 'category-create' %}
    <form class="search_item" name="form1" action="{% url 'BookApp:contentCreate' 'category-create' %}" method="POST" class="search_form" onsubmit="return check1()">
    {% endif %}

        {% csrf_token %}    <!-- CSRF(クロスサイト・リクエスト・フォージェリ)対策 -->
        <div class="gnavi__list2"><span class="index">TITLE</span>{{ form.title }}</div>

        <button type="submit" name="submit" class="button">Register</button>
    </form>


    <div class="content-list">
        {% if flag == 'stage-create' %}
        <p>Stage List</p>
        {% for item in obj %}
        <ul>
            <li>
                <span class="index">{{ item.title }}</span>
                <a href="{% url 'BookApp:contentDelete' item.id 'stage' %}" onclick="return check2()">Delete</a>
                <form name="form3" action="{% url 'BookApp:contentUpdate' item.id 'stage' %}" method="POST" enctype="multipart/form-data" onSubmit="return check3()">
                    {% csrf_token %}    <!-- CSRF(クロスサイト・リクエスト・フォージェリ)対策 -->
                    {{ form.title }}
                    <button type="submit" name="submit">Update</button>
                </form>
            </li>
        </ul>
        {% endfor %}
    
        {% elif flag == 'language-create' %}
        <p>Language List</p>
        {% for item in obj %}
        <ul>
            <li>
                <span class="index">{{ item.title }}</span>
                <a href="{% url 'BookApp:contentDelete' item.id 'language' %}" onclick="return check2()">Delete</a>
                <form name="form3" action="{% url 'BookApp:contentUpdate' item.id 'language' %}" method="POST" enctype="multipart/form-data" onSubmit="return check3()">
                    {% csrf_token %}    <!-- CSRF(クロスサイト・リクエスト・フォージェリ)対策 -->
                    {{ form.title }}
                    <button type="submit" name="submit">Update</button>
                </form>
            </li>
        </ul>
        {% endfor %}
    
        {% elif flag == 'category-create' %}
        <p>Category List</p>
        {% for item in obj %}
        <ul>
            <li>
                <span class="index">{{ item.title }}</span>
                <a href="{% url 'BookApp:contentDelete' item.id 'category' %}" onclick="return check2()">Delete</a>
                <form name="form3" action="{% url 'BookApp:contentUpdate' item.id 'category' %}" method="POST" enctype="multipart/form-data" onSubmit="return check3()">
                    {% csrf_token %}    <!-- CSRF(クロスサイト・リクエスト・フォージェリ)対策 -->
                    {{ form.title }}
                    <button type="submit" name="submit">Update</button>
                </form>
            </li>
        </ul>
        {% endfor %}
        {% endif %}
    </div>

</div>
{% endblock %}


<!-- Script -->
{% block js %}
    <script>
        function check1(){
            if(document.form1.title.value==""){
                alert("Input the content name.");
                return false;
            }
            else if(window.confirm('Do you register this content?')){ // 確認ダイアログを表示
                return true;
            }
            else{ // 「キャンセル」時の処理
                return false;
            }
        }

        function check2(){
            if(window.confirm('Do you delete this content?')){ // 確認ダイアログを表示
                return true;
            }
            else{ // 「キャンセル」時の処理
                return false;
            }
        }

        function check3(){
            if(window.confirm('Do you update this content?')){ // 確認ダイアログを表示
                return true;
            }
            else{ // 「キャンセル」時の処理
                return false;
            }
        }
    </script>
{% endblock %}